### ISSUE TITLE
BaseClasses.lib is not a valid Win32 app?

### ISSUE THREAD

**Issue by KingsBl4d3** [roman380/tmhare.mvps.org-vcam#2]
I apologize in advanced since I am an absolute complete novice at this, but I am trying to build a virtual camera that would be a simpler version of Sparkocam. The information you have here seems to be the best that I can get to help me. However, after following your steps, making sure that the directshow.props was correctly adjusted. But when I try to build the directshow.sln I get the pop up saying it's not a valid win 32 app? 

I'm sure it is something obvious, but any help would be appreciated!

**Comment by KingsBl4d3** [comment]
Nevermind.  I am just completely slow at this haha. I ran it through before and wasn't able to get the virtual camera option to show up in the Graph Studio. I just scrapped everything and was tired. I was hitting debugger not build.

**Comment by roman380** [comment]
BaseClasses.lib is a static library. You have to build it but it's not usable on its own, it is used by other projects/applications that links it in turn. You were probably confused because you hit Run in Visual Studio solution and somehow BaseClasses was set as "startup project". 

Intended use of this VCam project is to build the DLLs, register them via COM (regsvr32 or VS does it automatically if it is running elevated), then use externally through DirectShow based applications.

**Comment by paas10** [comment]
Hello Roman, can you give an example of any external application based in DirectShow which makes use of this VCam project? 
I already compiled this project successfully bu I'm confused about next steps to follow for finally get the Virtual Camera. 

I really appreciate your help in this topic.

**Comment by roman380** [comment]
1. Windows 10 SDK [GraphEdit](https://docs.microsoft.com/en-us/windows/win32/directshow/using-graphedit) or [GraphStudioNext](https://github.com/cplussharp/graph-studio-next#latest-build) should see the new filter when registered ([also mentioned in root README)[https://github.com/roman380/tmhare.mvps.org-vcam#how-to-use])
2. Windows SDK sample application [AmCap](https://docs.microsoft.com/en-us/windows/win32/directshow/amcap-sample), which you can built yourself from code [of the repository](https://github.com/roman380/Windows-classic-samples/tree/directshow/Samples/Win7Samples/multimedia/directshow) mentioned in item 1 [here](https://github.com/roman380/tmhare.mvps.org-vcam#updates). I updated not only BaseClasses there but also a few classic samples including AmCap.

![image](https://user-images.githubusercontent.com/11475832/113249952-4db8c000-92c8-11eb-9944-575f0052e009.png)

In both cases the application you are using should be of the same 32/64 bitness as the filter you built. Some further info on this is here: [Applicability of Virtual DirectShow Sources](https://alax.info/blog/1722).
