### ISSUE TITLE
Not showing up in discord or zoom

### ISSUE THREAD

**Issue by Lenart12** [roman380/tmhare.mvps.org-vcam#3]
I built the filter and registred it regsrv32 but only ms teams sees it as a webcam.

**Comment by roman380** [comment]
Please excuse my answering with links, it's just something I used to write about too many times:

- [Applicability of Virtual DirectShow Sources](http://alax.info/blog/1722)
- [DirectShow filter is not shown as input capture device](https://stackoverflow.com/a/49222795/868014)
- [64 bit Vivek's Virtual Camera](https://stackoverflow.com/a/52290063/868014)

**Comment by Lenart12** [comment]
Thanks for the quick answer. Didn't even think that 32bit isn't compatible everywhere. Maybe it wouldn't be so bad to put that in the readme. Also how stupid it is that media foundation cannot make a virtual source without a kernel device! Anyways, thanks for the links I apreciate it a bunch :^)
